### ISSUE TITLE
local_costmap is blank

### ISSUE THREAD

**Issue by dan9thsense** [googlecartographer/cartographer#1273]
I setup a ROS system with move_base and cartographer_ros, using the following cartographer_ros config parameters:
```
  map_frame = "map",
  tracking_frame = "imu_link",
  published_frame = "odom",
  odom_frame = "",
  provide_odom_frame = false,
  use_odometry = false,
```
Using these parameters in local_costmap_params.yaml:
```
local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   static_map: false
   rolling_window: true
```
And provide the odom frame (to base_footprint) from an odometry node independently.  In that case, all works well.

However, since I am not using odometry, I do not need an odom frame and would like to not bother running the odometry node, so I changed the cartographer config to:

```
  map_frame = "map",
  tracking_frame = "imu_link",
  published_frame = "base_footprint",
  odom_frame = "",
  provide_odom_frame = false,
  use_odometry = false,
```
I also changed local_costmap_params.yaml to:
```
local_costmap:
   global_frame: /map
   robot_base_frame: base_footprint
   static_map: false
   rolling_window: true
```

However, the local_costmap is blank.  The global costmap still looks good.  It uses these parameters:
```
global_costmap:
   global_frame: /map
   robot_base_frame: base_footprint
   static_map: true
   rolling_window: false
```

In general, it is better to use an odom frame with the local_costmap because the map frame can hop around while the odom frame is continuous.  So I tried making it work by publishing an odom frame with cartographer and having the local_costmap refer to that frame:

```
  map_frame = "map",
  tracking_frame = "imu_link",
  published_frame = "base_footprint",
  odom_frame = "odom",
  provide_odom_frame = true,
  use_odometry = false,
```
```
local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   static_map: false
   rolling_window: true
```

But with this configuration, the local_costmap remains blank.  Any ideas on what I am doing wrong?
