### ISSUE TITLE
Can't set TRAJECTORY_BUILDER_3D.use_intensities = true

### ISSUE THREAD

**Issue by jvavrek** [googlecartographer/cartographer#1955]
I'm trying to improve my SLAM results by including intensities:
```
TRAJECTORY_BUILDER_3D.use_intensities = true
```
but this quickly leads to
```
F0307 00:21:22.564245    83 local_trajectory_builder_3d.cc:134] Check failed: unsynchronized_data.ranges.size() == unsynchronized_data.intensities.size() (3706 vs. 0) Passed point cloud has inconsistent number of intensities and ranges.
```

(I can run SLAM when the flag is set to false, but the loop closure is not ideal.)

However, I can tell that my bag file contains a velodyne lidar `"intensity"` field:
```
rostopic echo /velodyne/velodyne_points data.bag
```

```
...
is_dense: True
header: 
  seq: 16
  stamp: 
    secs: 1709064083
    nsecs: 888649000
  frame_id: "velodyne"
height: 1
width: 3700
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
  - 
    name: "intensity"
    offset: 16
    datatype: 7
    count: 1
  - 
    name: "ring"
    offset: 20
    datatype: 4
    count: 1
is_bigendian: False
point_step: 32
...
```

and I can also use the `"intensity"` field in the `.h5` file we end up saving to disk further down the processing chain.

Is this feature not supported, or might I have misconfigured something?
