### ISSUE TITLE
memory leak possibility in cartographer

### ISSUE THREAD

**Issue by jihoonl** [googlecartographer/cartographer#525]
![cartographer_memory](https://user-images.githubusercontent.com/1556736/30363319-fd6fee72-985f-11e7-8f81-57a4facfbf95.png)

![submaps](https://user-images.githubusercontent.com/1556736/30363920-5532cbb4-9862-11e7-95bd-c98807a6185f.png)

It seems like memory consumption accumulates over time. I let cartographer run in pure localization mode more than 10hrs and the memory consumption permanently increased(from 1% to 10%). Potentially, memory leak somewhere?

**Comment by ojura** [comment]
I am suspecting this as well. I often need to restart rviz.

**Comment by wohe** [comment]
1. The RViz plugin is unrelated to this. If you restart RViz and that fixes your issue, this is pretty strong evidence that it is unrelated to memory consumption by the Cartographer node. @ojura If you think there is an issue with RViz as well, could you file a separate issue? I would suggest to do some debugging first though to verify that `cartographer_ros` is the likely cause, not e.g. graphics driver issues.
2. Before we jump to any conclusions, we should get more data. @jihoonl Could you try to get something like http://goog-perftools.sourceforge.net/doc/heap_profiler.html to work? It would be very useful to know what is consuming memory.
3. Note that growing memory consumption is expected. While we have removed the largest consumers of memory, we still keep the odometry forever for example. Even in the absence of odometry I expect memory consumption to accumulate, although I would guess a lot slower: `mapping::NestedVectorsById<>` keeps some data, member functions of `SparsePoseGraph` return nested vectors.

**Comment by ojura** [comment]
Whoops, I completely missed that it was the cartographer_node in `top`. Sorry. I will open an issue in the other repo. (By the way, if you haven't tried it, I highly recommend `htop` instead of `top`. You might need to install it using the package manager.)

**Comment by jihoonl** [comment]
heap profiling sounds good idea. I will try it. And note that I was not using odometry in this case. I agree that it could have been faster if odometry is in use.

**Comment by cschuet** [comment]
Closing. All further discussions on [#505](https://github.com/googlecartographer/cartographer_ros/issues/505). Thanks!

**Comment by jihoonl** [comment]
@cschuet #505 is a different symptom and cause. Could you reopen this?

As @wohe mentioned, this issue has nothing to do with rviz. It is an issue for memory leak in cartographer.

**Comment by cschuet** [comment]
Sorry I missed that. Did you have a chance to do heap profiling?

**Comment by jihoonl** [comment]
I haven't gotten a chance to investigate this issue yet due to the other prioritized works. But, I will update the issue as soon as I find something.

**Comment by cschuet** [comment]
Cool, thank you.

**Comment by jihoonl** [comment]
![memory](https://user-images.githubusercontent.com/1556736/33651942-d129a44e-da67-11e7-8386-a4e901c5b912.png)

Small updates on this issue.  We ran the latest version of cartographer and confirmed that memory consumption still increases in pure localization mode.

```
...
  - 
    trajectory_id: 0
    submap_index: 6
    submap_version: 188
    pose: 
      position: 
        x: 5.22731129042
        y: 3.52407170286
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.00519836008455
        w: 0.999986488435
  - 
    trajectory_id: 3
    submap_index: 52
    submap_version: 40
    pose: 
      position: 
        x: -0.145805460213
        y: 0.465069679046
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.999989935313
        w: 0.00448656576561
  - 
    trajectory_id: 3
    submap_index: 53
    submap_version: 22
    pose: 
      position: 
        x: -0.0236020480483
        y: 0.370183922529
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.999993183655
        w: 0.00369224092749
  - 
    trajectory_id: 3
    submap_index: 54
    submap_version: 2
    pose: 
      position: 
        x: 0.620850280505
        y: -0.111249160334
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.999989809537
        w: 0.00451451240516
---
```
